"""Build a figure gallery per phase, discovered from ``docs/_static/fN/``.

The verification notebooks write their figures outside the Sphinx source
directory, and the notebooks themselves are not versioned. Rather than
maintaining a page per phase by hand — which drifts the moment a figure is
renamed — this extension scans the directories at build time, copies what it
finds into ``_generated/`` and writes the pages.

Two consequences worth knowing. A phase that has produced no figures yet
produces no page, rather than an empty one. And a figure that is deleted
disappears from the documentation on the next build, with no page left
pointing at a missing image.

Filenames carry the ordering and the caption: ``f2_03_alphabet_acceptance.png``
becomes figure 3 of phase F2, captioned "Alphabet acceptance".
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from sphinx.application import Sphinx
from sphinx.util import logging

logger = logging.getLogger(__name__)

GENERATED = "_generated"
PHASE_DIR = "figures"


def _caption(stem: str) -> tuple[str, str]:
    """Split ``f2_03_alphabet_acceptance`` into its number and its caption."""
    parts = stem.split("_")
    if len(parts) >= 3 and parts[1].isdigit():
        number = parts[1].lstrip("0") or "0"
        words = " ".join(parts[2:]).replace("-", " ")
        return number, words[:1].upper() + words[1:]
    return "", stem.replace("_", " ")


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = text.strip() + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == body:
        return  # keep the mtime stable so Sphinx does not rebuild needlessly
    path.write_text(body, encoding="utf-8")


def generate(app: Sphinx) -> None:
    source_dir = Path(app.srcdir)
    root: Path = app.config.phase_figures_root
    titles: dict[str, str] = app.config.phase_figures_titles
    provenance: dict[str, str] = app.config.phase_figures_provenance
    default = "produced by the phase verification notebook"
    out = source_dir / GENERATED / PHASE_DIR

    if out.exists():
        shutil.rmtree(out)

    if not root.is_dir():
        logger.info("[phase_figures] %s does not exist, no galleries", root)
        _write(
            out / "index.md",
            "# Figures\n\nNo phase figures found under `docs/_static/`.",
        )
        return

    phases = sorted(
        directory
        for directory in root.iterdir()
        if directory.is_dir() and directory.name.startswith("f")
    )

    written: list[str] = []
    for phase in phases:
        images = sorted(phase.glob("*.png"))
        if not images:
            continue

        target = out / phase.name
        target.mkdir(parents=True, exist_ok=True)
        lines = [f"# {titles.get(phase.name, phase.name.upper())}", ""]
        lines.append(
            f"{len(images)} figures, "
            f"{provenance.get(phase.name, default)}, "
            "discovered at build time."
        )
        lines.append("")

        for image in images:
            shutil.copy2(image, target / image.name)
            number, caption = _caption(image.stem)
            heading = f"{number}. {caption}" if number else caption
            lines += [
                f"## {heading}",
                "",
                f"```{{figure}} {phase.name}/{image.name}",
                f":alt: {caption}",
                ":width: 100%",
                "",
                f"`docs/_static/{phase.name}/{image.name}`",
                "```",
                "",
            ]

        _write(out / f"{phase.name}.md", "\n".join(lines))
        written.append(phase.name)
        logger.info("[phase_figures] %s: %d figures", phase.name, len(images))

    index = [
        "# Figures",
        "",
        "Every figure below is generated by a phase verification notebook and "
        "collected from `docs/_static/` when the documentation is built. "
        "Nothing on these pages is maintained by hand.",
        "",
        "```{toctree}",
        ":maxdepth: 1",
        "",
    ]
    index += written
    index += ["```", ""]
    if not written:
        index = [
            "# Figures",
            "",
            "No phase figures found under `docs/_static/`.",
        ]
    _write(out / "index.md", "\n".join(index))


def setup(app: Sphinx) -> dict[str, Any]:
    app.add_config_value("phase_figures_root", Path("_static"), "env")
    app.add_config_value("phase_figures_titles", {}, "env")
    # Where a gallery's figures came from. Not every gallery is a delivery
    # phase, and a page that claims the wrong provenance is worse than one
    # that claims none.
    app.add_config_value("phase_figures_provenance", {}, "env")
    app.connect("builder-inited", generate)
    return {"version": "1.0", "parallel_read_safe": True}
